### ISSUE TITLE
testnet connection errors

### ISSUE THREAD

**Issue by dantrevino** [jcnelson/cli-blockstack#1]
## 502 bad gateway

Trying to use faucet at https://testnet.blockstack.org/sendBTC

Happy to ping someone/log this somewhere else, if required.  Funding with stacks worked fine.

**Comment by dantrevino** [comment]
## subdomain registrar connection fail
```
dan@singularity:~$ blockstack-cli -t register_subdomain dant.personal.id2 cd85c32c9761482f4f8f940a5412c42cbf2fd5d00829a55486a82ec704e9edb901 http://testnet.blockstack.org:4000 http://testnet.blockstack.org:30000
connectToGaiaHub: http://testnet.blockstack.org:4000/hub_info
uploadToGaiaHub: uploading profile.json to http://testnet.blockstack.org:4000
FetchError: request to http://testnet.blockstack.org:30000/index failed, reason: connect ETIMEDOUT 13.65.207.163:30000
    at ClientRequest.<anonymous> (/home/dan/projects/blockstack.js/node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:180:13)
    at Socket.socketErrorListener (_http_client.js:395:9)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
request to http://testnet.blockstack.org:30000/index failed, reason: connect ETIMEDOUT 13.65.207.163:30000
d
```

**Comment by jcnelson** [comment]
> subdomain registrar connection fail

Sorry about that---it was a configuration issue.
```
$ curl http://testnet.blockstack.org:30000/index
{"status":true}
```

**Comment by jcnelson** [comment]
> 502 bad gateway

Yup, that's a bug.  Should be fixed when the testnet reboots next.  Thanks for letting me know :+1:
