### ISSUE TITLE
CLI-Blockstack Balance Error

### ISSUE THREAD

**Issue by Anastik** [jcnelson/cli-blockstack#5]
When trying to query the balance for an address I get the following error:

Kitsanas-MacBook-Pro:cli-blockstack Kitsana.Dounglomchan$ blockstack-cli -t balance mv2H3QrUZJ3TFZpMNbaMUiUJ9vo2yT5SNY
TypeError: tokenAndBTC.push is not a function
    at /Users/Kitsana.Dounglomchan/cli-blockstack/lib/cli.js:2021:17
    at tryCatcher (/Users/Kitsana.Dounglomchan/cli-blockstack/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Kitsana.Dounglomchan/cli-blockstack/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/Kitsana.Dounglomchan/cli-blockstack/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/Kitsana.Dounglomchan/cli-blockstack/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/Kitsana.Dounglomchan/cli-blockstack/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/Kitsana.Dounglomchan/cli-blockstack/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/Kitsana.Dounglomchan/cli-blockstack/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/Kitsana.Dounglomchan/cli-blockstack/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
tokenAndBTC.push is not a function

**Comment by dantrevino** [comment]
```bash
dan@singularity:~$ blockstack-cli -t lookup kitsana.id2
TypeError: Cannot read property 'hasOwnProperty' of null
    at /home/dan/projects/cli-blockstack/lib/cli.js:247:18
    at tryCatcher (/home/dan/projects/cli-blockstack/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/dan/projects/cli-blockstack/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/dan/projects/cli-blockstack/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/dan/projects/cli-blockstack/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/dan/projects/cli-blockstack/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/dan/projects/cli-blockstack/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/home/dan/projects/cli-blockstack/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/home/dan/projects/cli-blockstack/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/home/dan/projects/cli-blockstack/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/home/dan/projects/cli-blockstack/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/dan/projects/cli-blockstack/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/dan/projects/cli-blockstack/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/dan/projects/cli-blockstack/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/dan/projects/cli-blockstack/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
Cannot read property 'hasOwnProperty' of null
d
```

**Comment by jcnelson** [comment]
Hey @Anastik @dantrevino ,

I think edc8190ceb063e0aa381e19d98c0fadb1d21b48b might fix this.  Thanks for reporting!  Also, I loved @Anastik's youtube tutorial ;)  Gives me some things to think about regarding usability.

**Comment by Anastik** [comment]
@jcnelson I'm glad you enjoyed it! Thanks for creating such a unique and exciting tool. I'm still learning, so I hope anything I can contribute will be of use.

**Comment by Anastik** [comment]
@jcnelson I was able to run the balance command; however, while it displayed the correct amount of satoshis it wasn't registering any of the Stacks associated with the address.

**Comment by Anastik** [comment]
And when I tried using the balance command on my actual Blockstack BTC address it said account not found. Is this only for the testnet or should it be working on the mainnet too?

**Comment by larrysalibra** [comment]
I'm experiencing the same problem:

```
Vanquish:cli-blockstack larry$ blockstack-cli balance mqGKyQvjJRrfmtwDqBQBLUYhqeY8HprxQ7
Error: Account not found
    at /Users/larry/git/cli-blockstack/lib/network.js:504:17
    at process._tickCallback (internal/process/next_tick.js:109:7)
Account not found
Vanquish:cli-blockstack larry$ blockstack-cli balance 
Invalid command arguments
Command: balance
Usage:
  balance ADDRESS 
  balance --address ADDRESS
          
  Query the balance of an account. Returns the balances of each kind of token 
  that the account owns. The balances will be in the *smallest possible 
  units* of the token (i.e. satoshis for BTC, microStacks for Stacks, etc.). 

Use "help" to list all commands.
Vanquish:cli-blockstack larry$ blockstack-cli balance --address mqGKyQvjJRrfmtwDqBQBLUYhqeY8HprxQ7
Error: Account not found
    at /Users/larry/git/cli-blockstack/lib/network.js:504:17
    at process._tickCallback (internal/process/next_tick.js:109:7)
Account not found
Vanquish:cli-blockstack larry$
```
