### ISSUE TITLE
error registering for sandbox and test domains

### ISSUE THREAD

**Issue by dantrevino** [jcnelson/cli-blockstack#6]
```bash
dan@singularity:~$ blockstack-cli -t register dant.test 6f83c1e77d5e5e58f22781481e5e363b7f3ecec155271ae926f4792726c9d83c01 9e7f008ef23bbbb441a35b2066fe8d1a36112accabf6e7f4ce4d0e701b276bcf01 http://testnet.blockstack.org:4000
Error
    at RemoteServiceError.BlockstackError (/home/dan/projects/blockstack.js/lib/errors.js:31:120)
    at new RemoteServiceError (/home/dan/projects/blockstack.js/lib/errors.js:90:127)
    at /home/dan/projects/blockstack.js/lib/network.js:273:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)

dan@singularity:~$ blockstack-cli -t register dant.sandbox 6f83c1e77d5e5e58f22781481e5e363b7f3ecec155271ae926f4792726c9d83c01 9e7f008ef23bbbb441a35b2066fe8d1a36112accabf6e7f4ce4d0e701b276bcf01 http://testnet.blockstack.org:4000
Error
    at RemoteServiceError.BlockstackError (/home/dan/projects/blockstack.js/lib/errors.js:31:120)
    at new RemoteServiceError (/home/dan/projects/blockstack.js/lib/errors.js:90:127)
    at /home/dan/projects/blockstack.js/lib/network.js:273:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)

```

**Comment by jcnelson** [comment]
Hey @dantrevino ,

Depending on the time, you might have simply caught the testnet server when it was rebooting (it does this at around 3:30 UTC).  Will look at the server logs and see what I can find.

**Comment by jcnelson** [comment]
Going to go ahead and close this for lack of updates.  AFAIK the testnet is working correctly.  Please re-open if the issue persists.  Thanks!
